# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        name: openembedded/bitbake
        ref: refs/tags/1.46.1
    
    # Runs a set of commands using the runners shell
    - name: setup
      run: |
        export PATH=$PWD/bitbake/bin:$PATH
        export PYTHONPATH=$PWD/bitbake/lib:$PYTHONPATH
        mkdir build
        mkdir build/conf
        echo "BBLAYERS ?= '$PWD/meta-base'" > build/conf/bblayers.conf
        cd build
        bitbake world
        
